"""add index on content_status_transitions content_id

Revision ID: a267b3c77051
Revises: 78a48a4ad922
Create Date: 2026-09-28 02:02:45.330329
"""

from collections.abc import Sequence

from alembic import op

revision: str = "a267b3c77051"
down_revision: str | None = "78a48a4ad922"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_content_status_transitions_content_id",
        "content_status_transitions",
        ["content_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_content_status_transitions_content_id", table_name="content_status_transitions"
    )
    # ### end Alembic commands ###
